### ISSUE TITLE
翻译进度追踪

### ISSUE THREAD

**Issue by ShenQingchuan** [rollup/rollup-docs-cn#1]
- [x] docs/index.md
- [x] docs/command-line-interface/index.md --- _Done by a6988f673_
- [x] docs/configuration-options/index.md --- 已认领 by @waynzh   https://github.com/rollup/rollup-docs-cn/pull/9
- [x] docs/es-module-syntax/index.md --- _Done by ee3258b_
- [x] docs/faqs/index.md --- 已认领
- [x] docs/introduction/index.md  --- _Done by b7a5517a1_
- [x] docs/javascript-api/index.md --- _Done by 48784eae_
- [x] docs/migration/index.md --- 已认领 #3 
- [x] docs/plugin-development/index.md --- 已认领 #4
- [x] docs/repl/index.md --- 已认领 #8
- [x] docs/tools/index.md --- 已认领
- [x] docs/troubleshooting/index.md --- 已认领 #6 
- [x] docs/tutorial/index.md --- 已认领 #2

**Comment by iDestin** [comment]
认领 `docs/tutorial/index.md`

**Comment by priority3** [comment]
认领 `docs/migration/index.md`

**Comment by c0dedance** [comment]
认领  docs/faqs/index.md

**Comment by waynzh** [comment]
认领 docs/configuration-options/index.md

**Comment by SnowingFox** [comment]
认领 docs/plugin-development/index.md

**Comment by yixiaojiu** [comment]
认领 docs/troubleshooting/index.md

**Comment by SnowingFox** [comment]
认领  docs/repl/index.md

**Comment by ShenQingchuan** [comment]
目前初稿翻译已经全部完成。
